=== AlCaponi/XML-Ferienwohnung/src/XMLProject_Team02/bookings_list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="zipcode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="4"/>
				<xs:maxLength value="5"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street" type="xs:string"/>
	<xs:element name="startdate" type="xs:date"/>
	<xs:element name="sno" type="xs:byte"/>
	<xs:element name="lastname" type="xs:string"/>
	<xs:element name="firstname" type="xs:string"/>
	<xs:element name="enddate" type="xs:date"/>
	<xs:element name="countrycode" type="xs:string"/>
	<xs:element name="city" type="xs:string"/>
	<xs:element name="bookings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="booking"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="booking">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="startdate"/>
				<xs:element ref="enddate"/>
				<xs:element ref="booker"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:byte" use="required"/>
			<xs:attribute name="fewoid" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="booker">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="firstname" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="lastname" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="street" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="sno" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="countrycode" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="zipcode" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="city" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AlCaponi/XML-Ferienwohnung/XML-DB/bookings_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bookings_list.xsd">
	<booking id="01" fewoid="01">
		<startdate>2015-01-01</startdate>
		<enddate>2015-01-05</enddate>
		<booker>
			<firstname>Michael</firstname>
			<lastname>Knight</lastname>
			<street>Schokoladengasse Ecke abgebissen</street>
			<sno>5</sno>
			<zipcode>1234</zipcode>
			<countrycode>CH</countrycode>
			<city>Rockcity</city>
		</booker>
	</booking>
</bookings>

=== AlCaponi/XML-Ferienwohnung/src/XMLProject_Team02/bookings_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bookings_list.xsl"?>
<bookings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bookings_list.xsd">
	<booking id="01" fewoid="01">
		<startdate>2015-01-01</startdate>
		<enddate>2015-01-05</enddate>
		<booker>
			<firstname>Michael</firstname>
			<lastname>Knight</lastname>
			<street>Schokoladengasse Ecke abgebissen</street>
			<sno>5</sno>
			<zipcode>1234</zipcode>
			<countrycode>CH</countrycode>
			<city>Rockcity</city>
		</booker>
	</booking>
	<booking id="02" fewoid="01">
		<startdate>2015-01-10</startdate>
		<enddate>2015-01-15</enddate>
		<booker>
			<firstname>Daniel</firstname>
			<lastname>Schmid</lastname>
			<street>Ecke abgebissen</street>
			<sno>9</sno>
			<zipcode>9876</zipcode>
			<countrycode>DE</countrycode>
			<city>Rockcity</city>
		</booker>
	</booking>
	<booking id="03" fewoid="02">
		<startdate>2015-04-04</startdate>
		<enddate>2015-05-05</enddate>
		<booker>
			<firstname>Hans</firstname>
			<lastname>Bauer</lastname>
			<street>Landstrasse</street>
			<sno>99</sno>
			<zipcode>8888</zipcode>
			<countrycode>CH</countrycode>
			<city>Langnau</city>
		</booker>
	</booking>
	<booking id="04" fewoid="02">
		<startdate>2015-09-09</startdate>
		<enddate>2015-09-22</enddate>
		<booker>
			<firstname>Martin</firstname>
			<lastname>Schmidt</lastname>
			<street>Winkelgasse</street>
			<sno>123a</sno>
			<zipcode>12345</zipcode>
			<countrycode>DE</countrycode>
			<city>Hogwarts</city>
		</booker>
	</booking>
	<booking id="05" fewoid="01">
		<startdate>2015-12-12</startdate>
		<enddate>2015-12-15</enddate>
		<booker>
			<firstname>Rainer</firstname>
			<lastname>Meier</lastname>
			<street>Hauptstrasse</street>
			<sno>12</sno>
			<zipcode>4040</zipcode>
			<countrycode>CH</countrycode>
			<city>Basel</city>
		</booker>
	</booking>
	<booking id="08" fewoid="02">
		<startdate>2015-11-11</startdate>
		<enddate>2015-12-12</enddate>
		<booker>
			<firstname>Rukshan</firstname>
			<lastname>Srirangarajah</lastname>
			<street>Maihofstrasse</street>
			<sno>12</sno>
			<zipcode>6004</zipcode>
			<countrycode>CH</countrycode>
			<city>Luzern</city>
		</booker>
	</booking>
	<booking id="08" fewoid="02"><startdate>2015-11-11</startdate><enddate>2015-12-12</enddate><booker><firstname>Rukshan</firstname><lastname>Srirangarajah</lastname><street>Maihofstrasse</street><sno>12</sno><zipcode>6004</zipcode><countrycode>CH</countrycode><city>Luzern</city></booker></booking><booking id="09" fewoid="03"><startdate>2015-04-20</startdate><enddate>2015-05-11</enddate><booker><firstname>Anton</firstname><lastname>Test</lastname><street>Teststrasse</street><sno>9</sno><zipcode>4478</zipcode><countrycode>CH</countrycode><city>Liestal</city></booker></booking><booking id="10" fewoid="@id"><startdate>2016-01-01</startdate><enddate>2016-02-02</enddate><booker><firstname>FINALFirstname</firstname><lastname>FINALLastname</lastname><street>FINALStreet</street><sno>FINALNumber</sno><zipcode>FINALZip</zipcode><countrycode>FINALCC</countrycode><city>FINALCity</city></booker></booking><booking id="11" fewoid="object/@id"><startdate>2016-07-07</startdate><enddate>2016-08-08</enddate><booker><firstname>Firstname</firstname><lastname>Lastname</lastname><street>Street</street><sno>3</sno><zipcode>3993</zipcode><countrycode>CH</countrycode><city>ajsdfl</city></booker></booking><booking id="13" fewoid="02"><startdate>2017-09-07</startdate><enddate>2017-09-10</enddate><booker><firstname>Test</firstname><lastname>Teste</lastname><street>Testsr</street><sno>34</sno><zipcode>4998</zipcode><countrycode>CH</countrycode><city>Aargau</city></booker></booking></bookings>
