=== AlCaponi/XML-Ferienwohnung/src/XMLProject_Team02/fewo_list.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fewo">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="object">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title"></xs:element>
              <xs:element name="descr"></xs:element>
              <xs:element name="dim"></xs:element>
              <xs:element name="rooms"></xs:element>
              <xs:element name="priceByDay"></xs:element>
              <xs:element name="images">
                <xs:complexType>
                  <xs:sequence maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="image"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlCaponi/XML-Ferienwohnung/src/XMLProject_Team02/fewo_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="fewo_list.xsl"?>
<fewo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fewo_list.xsd">
  <object id="01">
    <title>Ferienwohnung Pilatusblick</title>
    <descr>Wundervolle 3-Zimmer Wohnung für alle die sich was wert sind</descr>
    <dim>90 m²</dim>
    <rooms>3</rooms>
    <priceByDay>85.00</priceByDay>
    <images>
      <image>fewo_images/test1.png</image>
      <image>fewo_images/test2.png</image>
      <image>fewo_images/test3.png</image>
      <image>fewo_images/test4.png</image>
      <image>fewo_images/test5.png</image>
    </images>
  </object>
  <object id="02">
    <title>Ferienwohnung Rigi</title>
    <descr>Wundervolle 1-Zimmer Wohnung für Paare</descr>
    <dim>40 m²</dim>
    <rooms>1</rooms>
    <priceByDay>40.00</priceByDay>
    <images>
      <image>fewo_images/test6.png</image>
      <image>fewo_images/test7.png</image>
      <image>fewo_images/test8.png</image>
      <image>fewo_images/test9.png</image>
      <image>fewo_images/test10.png</image>
    </images>
  </object>
</fewo>

=== AlCaponi/XML-Ferienwohnung/XML-DB/fewo_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<fewo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fewo_list.xsd">
  <object id="01">
    <title>Ferienwohnung Pilatusblick</title>
    <descr>Wundervolle 3-Zimmer Wohnung f√ºr alle die sich was Wert sind</descr>
    <dim>90qm</dim>
    <rooms>3</rooms> 
    <priceByDay>85.00</priceByDay>
    <images>
       <image>fewo_images/test1.png</image>
       <image>fewo_images/test2.png</image>
       <image>fewo_images/test3.png</image>
       <image>fewo_images/test4.png</image>
       <image>fewo_images/test5.png</image>
    </images>
  </object>
</fewo>
